2025-08-27 11:07:12,537 INFO    MainThread:844297 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts/wandb/run-20250827_110711-gocm0h04/logs/debug.log
2025-08-27 11:07:12,539 INFO    MainThread:844297 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /global/cfs/cdirs/m4334/sferrett/monsoon-sr/scripts/wandb/run-20250827_110711-gocm0h04/logs/debug-internal.log
2025-08-27 11:07:12,539 INFO    MainThread:844297 [wandb_init.py:init():830] calling init triggers
2025-08-27 11:07:12,540 INFO    MainThread:844297 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'name': 'exp_3', 'input_variables': ['capeprofile'], 'loss_function': 'L1Loss', 'n_params': 48577, 'batch_size': 64000, 'patience': 3, '_wandb': {}}
2025-08-27 11:07:12,540 INFO    MainThread:844297 [wandb_init.py:init():871] starting backend
2025-08-27 11:07:12,540 INFO    MainThread:844297 [wandb_init.py:init():874] sending inform_init request
2025-08-27 11:07:12,546 INFO    MainThread:844297 [wandb_init.py:init():882] backend started and connected
2025-08-27 11:07:12,550 INFO    MainThread:844297 [wandb_init.py:init():953] updated telemetry
2025-08-27 11:07:12,735 INFO    MainThread:844297 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-27 11:07:13,005 INFO    MainThread:844297 [wandb_init.py:init():1029] starting run threads in backend
2025-08-27 11:07:14,404 INFO    MainThread:844297 [wandb_run.py:_console_start():2458] atexit reg
2025-08-27 11:07:14,404 INFO    MainThread:844297 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-08-27 11:07:14,405 INFO    MainThread:844297 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-08-27 11:07:14,407 INFO    MainThread:844297 [wandb_run.py:_redirect():2398] Redirects installed.
2025-08-27 11:07:14,408 INFO    MainThread:844297 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-27 11:09:57,924 INFO    MsgRouterThr:844297 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 3 handles.
